In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[4]

4

In [5]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [13]:
arr[0:5] = 100

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
arr = np.arange(0,11)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_of_arr = arr[0:6]

In [19]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [20]:
slice_of_arr[:] = 99

In [21]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
#this means slicing is not a copy of a part of an array
# it is just a view of the part of the array
#original values also get changed on the parent array

In [24]:
#indexing of a 2D ARRAY

In [26]:
arr_2d = np.array([[5,10,10],[1,4,6],[24,49,74]])

In [27]:
arr_2d

array([[ 5, 10, 10],
       [ 1,  4,  6],
       [24, 49, 74]])

In [28]:
arr_2d[0][1]

10

In [29]:
arr_2d[0]   #will index an entire row

array([ 5, 10, 10])

In [30]:
arr_2d[1][1]

4

In [31]:
arr_2d[1,1]

4

In [32]:
#if you want sub matrices from the matrix

In [33]:
arr_2d

array([[ 5, 10, 10],
       [ 1,  4,  6],
       [24, 49, 74]])

In [34]:
arr_2d[:2,1:]

array([[10, 10],
       [ 4,  6]])

In [35]:
arr_2d[1:,:]

array([[ 1,  4,  6],
       [24, 49, 74]])

In [36]:
#conditional Selection

In [37]:
arr = np.arange(1,11)

In [38]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [40]:
bool_arr = arr > 5

In [41]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [42]:
arr[bool_arr]              #wil now give values only wherever it is true

array([ 6,  7,  8,  9, 10])

In [43]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [45]:
arr[arr<3]

array([1, 2])

In [46]:
arr_2d = np.arange(50).reshape(5,10)

In [47]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [55]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])