In [4]:
my_list = [1,2,3]

In [5]:
my_list

[1, 2, 3]

In [6]:
import numpy as np

In [9]:
arr = np.array(my_list)

In [10]:
arr

array([1, 2, 3])

In [11]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
#see the difference above

In [15]:
np.arange(0,10,0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09,
       1.1 , 1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 ,
       1.21, 1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31,
       1.32, 1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42,
       1.43, 1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
np.arange(0,11,2)         #to get even numbers

array([ 0,  2,  4,  6,  8, 10])

In [21]:
np.zeros(3)        #single digit will give us one dimensional vector out

array([0., 0., 0.])

In [22]:
# we can also give a tuple (rows,columns)
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((8,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
#linspace gives evenly spaced number over a range
#not to be confused with arange
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [26]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [27]:
np.linspace(0,100,1000)

array([  0.        ,   0.1001001 ,   0.2002002 ,   0.3003003 ,
         0.4004004 ,   0.5005005 ,   0.6006006 ,   0.7007007 ,
         0.8008008 ,   0.9009009 ,   1.001001  ,   1.1011011 ,
         1.2012012 ,   1.3013013 ,   1.4014014 ,   1.5015015 ,
         1.6016016 ,   1.7017017 ,   1.8018018 ,   1.9019019 ,
         2.002002  ,   2.1021021 ,   2.2022022 ,   2.3023023 ,
         2.4024024 ,   2.5025025 ,   2.6026026 ,   2.7027027 ,
         2.8028028 ,   2.9029029 ,   3.003003  ,   3.1031031 ,
         3.2032032 ,   3.3033033 ,   3.4034034 ,   3.5035035 ,
         3.6036036 ,   3.7037037 ,   3.8038038 ,   3.9039039 ,
         4.004004  ,   4.1041041 ,   4.2042042 ,   4.3043043 ,
         4.4044044 ,   4.5045045 ,   4.6046046 ,   4.7047047 ,
         4.8048048 ,   4.9049049 ,   5.00500501,   5.10510511,
         5.20520521,   5.30530531,   5.40540541,   5.50550551,
         5.60560561,   5.70570571,   5.80580581,   5.90590591,
         6.00600601,   6.10610611,   6.20620621,   6.30

In [28]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
#to create arrays of random numbers
np.random.rand(5)             #for number between zero to one

array([0.27654869, 0.50294867, 0.42453463, 0.0268356 , 0.34576602])

In [31]:
np.random.rand(5,5)    #no need  to give tuple

array([[0.49140312, 0.65490068, 0.35744885, 0.73584102, 0.40143655],
       [0.29553036, 0.65649366, 0.6842747 , 0.03165529, 0.52552639],
       [0.11296861, 0.11844116, 0.64593987, 0.27833681, 0.60942113],
       [0.54555719, 0.21718326, 0.12049503, 0.30173336, 0.41887179],
       [0.27663623, 0.14610384, 0.86048858, 0.15680858, 0.02473614]])

In [32]:
np.random.randn(2)

array([-0.35370489,  0.44011963])

In [33]:
np.random.randn(8,8)

array([[ 1.73432643,  2.25236128, -0.71543183,  0.32487064, -0.48555371,
        -1.04140523,  0.5414251 , -1.09787181],
       [ 0.21688999,  0.24846759, -0.40842602, -0.62938846,  1.4607964 ,
         0.90251028,  0.81429306, -1.68595164],
       [-0.87532683, -2.23178676, -0.1472347 , -0.71331787, -0.1461523 ,
        -0.25115417,  0.35432182, -0.47189765],
       [ 0.54952081, -0.06050509, -1.49127931, -0.11368977, -0.13161463,
         0.50035764,  1.24343821,  0.29413052],
       [ 0.58573379, -1.3981355 , -0.4937045 ,  0.16119646,  2.56973215,
         0.33882824,  0.24950244,  1.28862828],
       [-0.87191686,  1.85387386,  0.87014822,  0.78536451, -0.15137162,
         0.06131373,  0.80607938, -0.64938724],
       [-0.25023184, -0.2091592 ,  1.35581178,  0.44654296,  0.21396385,
         0.59271701, -0.39061236, -0.68950359],
       [-0.70292454, -0.01136869, -0.02793242,  1.95304999, -0.86351894,
         0.31258934, -0.33828448, -1.6283253 ]])

In [35]:
#random integers
np.random.randint(1,100)     #we will get random number between 1 to 100

29

In [36]:
np.random.randint(1,100,20)        #getting 20 random numbers

array([24, 82,  4, 15, 63, 76, 65, 56, 70, 67, 49, 50, 19, 73, 59, 23, 71,
       77, 74, 75])

In [37]:
arr = np.arange(25)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
ranarr = np.random.randint(0,50,10)

In [40]:
ranarr

array([ 3, 49,  0, 42, 47, 49, 14, 20, 19, 34])

In [41]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
ranarr.max()

49

In [44]:
ranarr.min()

0

In [45]:
ranarr

array([ 3, 49,  0, 42, 47, 49, 14, 20, 19, 34])

In [46]:
ranarr.argmax() #will give index location of the max value

1

In [47]:
arr.shape

(25,)

In [48]:
arr = arr.reshape(5,5)

In [49]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
arr.shape

(5, 5)

In [52]:
arr.dtype

dtype('int32')

In [53]:
from numpy.random import randint

In [54]:
randint(2,10)

5

In [56]:
randint(3,100,5)

array([55, 88, 77, 31, 23])