In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
#universal functions are the functions that apply to every value in the arrray

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [10]:
#some binary functions too
A = np.random.randn(10)
A

array([ 0.60650004,  1.06372987, -0.90084724, -0.68584761, -0.45880203,
       -0.65612733,  0.3411177 ,  0.61303835, -0.15840088, -1.50338258])

In [11]:
B = np.random.randn(10)
B

array([ 0.40168927,  0.78515011, -1.31340871, -1.03949685,  0.03852549,
       -0.45941566, -1.7515036 ,  0.35716885,  0.22040447,  0.40743568])

In [13]:
#binary functions
np.add(A,B)

array([ 1.00818931,  1.84887998, -2.21425595, -1.72534446, -0.42027654,
       -1.11554299, -1.4103859 ,  0.9702072 ,  0.06200358, -1.0959469 ])

In [15]:
np.maximum(A,B)   #compares corresponding terms and tell the values

array([ 0.60650004,  1.06372987, -0.90084724, -0.68584761,  0.03852549,
       -0.45941566,  0.3411177 ,  0.61303835,  0.22040447,  0.40743568])

In [16]:
np.minimum(A,B)

array([ 0.40168927,  0.78515011, -1.31340871, -1.03949685, -0.45880203,
       -0.65612733, -1.7515036 ,  0.35716885, -0.15840088, -1.50338258])

In [20]:
#there are many more universal functions (ufuncs) we can check thru web also.

We can also open a website through JUPYTER notebook. CHECK THIS:

In [19]:
website = 'www.google.com'                  #Define the link
import webbrowser                           #import the web browser
webbrowser.open(website)                    #call the web browser to open that link.

True

lecture 11 completed!! YAYYY!!!