In [1]:
print ("meri rabb to aa ikko mang ve, meri rabb to aa ikko mang ve ho mauka tere naal milerehn nu")

meri rabb to aa ikko mang ve, meri rabb to aa ikko mang ve ho mauka tere naal milerehn nu


In [2]:
print ("mera vi ta chitt krdae teri kaali range vichh behn nu")

mera vi ta chitt krdae teri kaali range vichh behn nu


In [3]:
print('Shift+Enter')

Shift+Enter


In [11]:
L = [1,2,3]
print(L)

[1, 2, 3]


In [12]:
import numpy as np
my_list1 = [1,2,3,4]

In [13]:
my_array1 = np.array(my_list1)
my_array1

array([1, 2, 3, 4])

In [14]:
my_list2 = [11,22,33,44]

In [15]:
my_lists = [my_list1,my_list2]

In [17]:
my_array2 = np.array(my_lists)
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [19]:
my_array2.shape

(2, 4)

In [20]:
my_array2.dtype

dtype('int32')

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
my_zeros_array = np.zeros(5)

In [25]:
my_zeros_array.dtype

dtype('float64')

In [26]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
np.ones([11,11])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [29]:
np.empty(5)

array([3.22651328e-307, 1.89144180e-307, 8.90071984e-308, 6.23053954e-307,
       1.78020848e-306])

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [35]:
np.arange(5,50,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])