In [1]:
import numpy as np

In [2]:
5/2

2.5

In [3]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [4]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [5]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [6]:
np.multiply(arr1,arr1)

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [8]:
arr1 - 2

array([[-1,  0,  1,  2],
       [ 6,  7,  8,  9]])

In [9]:
1/arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [10]:
arr1**4

array([[    1,    16,    81,   256],
       [ 4096,  6561, 10000, 14641]], dtype=int32)

In [11]:
#mathematical operations on arrays!