In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [10]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [11]:
arr[0:5] = 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
arr = np.arange(0,11)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
slice_of_arr[:] = 99

In [17]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

this hasn't created a separate array.. instead it is just a view of original array.
this avoids memory problem as we do not have several copies of arrays floating around, we just have only one copy of array.

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
#hence it has affected original array

In [21]:
#if we dont want that we need to create separate array explicitly

In [22]:
arr_copy = arr.copy()

In [23]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

INDEXING IN A 2 DIMENSIONAL ARRAY.

In [26]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [27]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
arr_2d[1] #if we want any row just type its index in square brackets

array([20, 25, 30])

In [29]:
arr_2d[0]

array([ 5, 10, 15])

In [30]:
#for individual element value
#[row][column]
arr_2d[1][1]

25

In [31]:
#harnessing 2*2 array from this array

In [35]:
arr_2d[:2,1:]           #rows,columns

array([[10, 15],
       [25, 30]])

In [36]:
arr_2d[1:2,1]     #my test to get a particular element in the form of an array

array([25])

#fancy indexing

In [58]:
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [59]:
arr_length = arr2d.shape[1]

In [60]:
arr_length

10

In [74]:
for i in range(arr_length):
    arr2d[i] = i

In [75]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

SELF EXPLORING: IF ARRAY ELEMENT IS EQUAL TO THE SQUARE OF SUM OF ITS ROW NUMBER AND COLUMN NUMBER.

In [76]:
arr_visvash = np.zeros((10,10))
arr_visvash

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [79]:
arr_total_rows = arr_visvash.shape[0]
arr_total_cols = arr_visvash.shape[1]

In [83]:
for i in range(arr_total_rows):
    for j in range(arr_total_cols):
        arr_visvash[i][j] = (i+j+2)*(i+j+2)

In [84]:
arr_visvash

array([[  4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100., 121.],
       [  9.,  16.,  25.,  36.,  49.,  64.,  81., 100., 121., 144.],
       [ 16.,  25.,  36.,  49.,  64.,  81., 100., 121., 144., 169.],
       [ 25.,  36.,  49.,  64.,  81., 100., 121., 144., 169., 196.],
       [ 36.,  49.,  64.,  81., 100., 121., 144., 169., 196., 225.],
       [ 49.,  64.,  81., 100., 121., 144., 169., 196., 225., 256.],
       [ 64.,  81., 100., 121., 144., 169., 196., 225., 256., 289.],
       [ 81., 100., 121., 144., 169., 196., 225., 256., 289., 324.],
       [100., 121., 144., 169., 196., 225., 256., 289., 324., 361.],
       [121., 144., 169., 196., 225., 256., 289., 324., 361., 400.]])

Hurrah! I got that.

In [85]:
#another example of fancy indexing

In [88]:
arr_visvash[[2,4,6,8]]

array([[ 16.,  25.,  36.,  49.,  64.,  81., 100., 121., 144., 169.],
       [ 36.,  49.,  64.,  81., 100., 121., 144., 169., 196., 225.],
       [ 64.,  81., 100., 121., 144., 169., 196., 225., 256., 289.],
       [100., 121., 144., 169., 196., 225., 256., 289., 324., 361.]])

In [90]:
arr_visvash[[4,5,1,2,5]] #remember the order in which you enter the row number.

array([[ 36.,  49.,  64.,  81., 100., 121., 144., 169., 196., 225.],
       [ 49.,  64.,  81., 100., 121., 144., 169., 196., 225., 256.],
       [  9.,  16.,  25.,  36.,  49.,  64.,  81., 100., 121., 144.],
       [ 16.,  25.,  36.,  49.,  64.,  81., 100., 121., 144., 169.],
       [ 49.,  64.,  81., 100., 121., 144., 169., 196., 225., 256.]])

LECTURE 9 COMPLETED!! yayyyyyyy!!!