In [2]:
# from sklearn.family import Linear Regression

In [3]:
from sklearn.linear_model import LinearRegression

In [4]:
#from sklearn. shift+tab

In [5]:
import numpy as np

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X,y = np.arange(10).reshape((5,2)),range(5)

In [17]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [18]:
list(y)

[0, 1, 2, 3, 4]

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [20]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [21]:
X_train

array([[8, 9],
       [2, 3],
       [6, 7]])

In [22]:
y_train

[4, 1, 3]

In [23]:
y_test

[0, 2]

In [24]:
X_test

array([[0, 1],
       [4, 5]])

In [28]:
#model.fit(X_train,y_train)

AttributeError: 'numpy.ndarray' object has no attribute 'fit'

In [26]:
#predictions = model.predict(X_test)

NameError: name 'model' is not defined

In [1]:
#google search "scikit learn algorithm cheat sheet"